services:
  configserver:
    image: alexandevcwa/cafetito-ms-config-server:1.0.0
    container_name: configserver-ms
    ports:
      - "1001:1001"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent configserver:1001/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 5s
    extends:
      service: network-config
      file: common-config.yml
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${SERVER_GIT_URI}

####################################################################################################################
  eurekaserver:
    image: alexandevcwa/cafetito-ms-eureka-server:1.0.0
    container_name: eurekaserver-ms
    ports:
      - "1002:1002"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent eurekaserver:1002/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 5s
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      service: network-config
      file: common-config.yml

####################################################################################################################
  auth:
    image: alexandevcwa/cafetito-ms-auth:1.1.0
    container_name: auth-ms
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent auth:8080/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml
    environment:
      JWT_SECRET: ${JWT_SECRET}

####################################################################################################################
  nits:
    image: alexandevcwa/cafetito-ms-nits:1.0.1
    container_name: nits-ms
    ports:
      - "8081:8081"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent nits:8081/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  accounts:
    image: alexandevcwa/cafetito-ms-accounts:1.0.0
    container_name: accounts-ms
    ports:
      - "8082:8082"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent accounts:8082/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  users:
    image: alexandevcwa/cafetito-ms-users:1.0.0
    container_name: users-ms
    ports:
      - "8083:8083"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent users:8083/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  catalogs:
    image: alexandevcwa/cafetito-ms-catalogs:1.4.0
    container_name: catalogs-ms
    ports:
      - "8084:8084"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent catalogs:8084/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  transports:
    image: alexandevcwa/cafetito-ms-transports:1.2.0
    container_name: transports-ms
    ports:
      - "8085:8085"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent transports:8085/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      catalogs:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  weighings:
    image: alexandevcwa/cafetito-ms-weighings:1.2.0
    container_name: weighings-ms
    ports:
      - "8086:8086"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent weighings:8086/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      catalogs:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  transporters:
    image: alexandevcwa/cafetito-ms-transporters:1.0.1
    container_name: transporters-ms
    ports:
      - "8087:8087"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent transporters:8087/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      catalogs:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  pilots:
    image: alexandevcwa/cafetito-ms-pilots:1.3.0
    container_name: pilots-ms
    ports:
      - "8088:8088"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent pilots:8088/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      catalogs:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  beneficion_transportistas:
    image: alexandevcwa/cafetito-ms-beneficio-transportistas:1.1.0
    container_name: beneficion_transportistas-ms
    ports:
      - "8089:8089"
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent beneficion_transportistas:8089/api/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml

####################################################################################################################
  gateway:
    image: alexandevcwa/cafetito-ms-gateway:1.1.0
    container_name: gatewayserver-ms
    ports:
      - "1000:1000"
    healthcheck:
      test: "curl --fail --silent gateway:1000/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 5s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      auth:
        condition: service_healthy
    extends:
      service: microservice-config
      file: common-config.yml
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}

####################################################################################################################
networks:
  cafetito-network:
    external: true
